name: Sync issue to Azure DevOps work item

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: cephalin/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "syncedorg"
          ado_project: "syncedproject"
          ado_wit: "Issue"
          ado_new_state: "To Do"
          ado_close_state: "Done"
          ado_bypassrules: true
          id_mapping_url: "${{ secrets.ID_MAPPING_URL }}"
          id_mapping_pat: "${{ secrets.ID_MAPPING_PAT }}"
          id_mapping_query: '$.aad.userPrincipalName'
